import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme/tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  scroll: { flexGrow: 1, paddingHorizontal: spacing.md },
  page: { width: '100%', maxWidth: 1080, alignSelf: 'center', paddingBottom: spacing.lg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingVertical: spacing.lg,
  },
  wordmarkRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  brandDot: {
    width: 12,
    height: 16,
    borderRadius: radius.pill,
    backgroundColor: colors.brandStrong,
    transform: [{ rotate: '-15deg' }],
  },
  wordmark: { fontSize: 23, fontWeight: '900', letterSpacing: 1, color: colors.brandStrong },
  previewBadge: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  previewBadgeText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
  hero: {
    backgroundColor: colors.hero,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  heroWide: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.xl,
  },
  heroCopy: { flex: 1, gap: spacing.md },
  eyebrow: {
    color: colors.brandStrong,
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '800',
    letterSpacing: 1,
  },
  heroTitle: { color: colors.text, ...typography.display, fontWeight: '800', letterSpacing: -1.3 },
  heroDescription: { color: colors.textSecondary, ...typography.body },
  heroNote: { color: colors.brandStrong, ...typography.caption, marginTop: spacing.sm },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  sectionTitle: {
    color: colors.text,
    ...typography.title,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  body: { color: colors.text, ...typography.body },
  caption: { color: colors.textSecondary, ...typography.caption, flexShrink: 1 },
  selectionColumns: { gap: spacing.xl },
  columnsWide: { flexDirection: 'row', alignItems: 'flex-start' },
  choicesColumn: { flex: 1, gap: spacing.sm },
  speciesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md },
  speciesCard: {
    flexGrow: 1,
    flexBasis: '46%',
    minWidth: 112,
    padding: spacing.md,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: radius.md,
    gap: spacing.xs,
    minHeight: 155,
  },
  fullWidthCard: { flexBasis: '100%' },
  speciesSelected: { borderColor: colors.brandStrong, backgroundColor: colors.brandSoft },
  speciesCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  speciesIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
  },
  speciesSymbol: { fontSize: 27, fontWeight: '600' },
  selectionIndicator: { color: colors.textSecondary, fontSize: 22, fontWeight: '700' },
  selectedIndicator: { color: colors.brandStrong },
  speciesName: { color: colors.text, fontSize: 18, lineHeight: 26, fontWeight: '800' },
  selectedLabel: {
    color: colors.brandStrong,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: spacing.xs,
  },
  formColumn: { flex: 1, gap: spacing.sm },
  formColumnWide: { borderLeftWidth: 1, borderLeftColor: colors.border, paddingLeft: spacing.xl },
  inputLabel: {
    color: colors.text,
    ...typography.caption,
    fontWeight: '700',
    marginTop: spacing.lg,
  },
  nameInput: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.text,
    backgroundColor: colors.background,
    padding: spacing.md,
    ...typography.body,
  },
  inputError: { borderColor: colors.danger },
  inputHintRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  inputHint: { color: colors.textSecondary, fontSize: 12, lineHeight: 18 },
  formSummary: {
    padding: spacing.md,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    gap: spacing.sm,
    marginVertical: spacing.md,
  },
  formSummaryTitle: { color: colors.text, ...typography.caption, fontWeight: '700' },
  primaryButton: {
    minHeight: 56,
    backgroundColor: colors.brandStrong,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    padding: spacing.md,
  },
  primaryButtonText: {
    color: colors.surface,
    ...typography.body,
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 1,
  },
  buttonPending: { opacity: 0.75 },
  pressed: { opacity: 0.8 },
  footnote: { color: colors.textSecondary, fontSize: 12, lineHeight: 20, marginTop: spacing.sm },
  errorText: { color: colors.danger, ...typography.caption, paddingVertical: spacing.sm },
  loadingCard: {
    padding: spacing.xl,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    alignItems: 'center',
    gap: spacing.md,
  },
  bottomNote: { alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.xl },
  bottomNoteTitle: { color: colors.text, ...typography.body, fontWeight: '700' },
  footer: { paddingTop: spacing.lg, borderTopWidth: 1, borderTopColor: colors.border },
  footerText: { color: colors.textSecondary, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  backButton: {
    minHeight: 48,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    paddingRight: spacing.md,
    paddingBottom: spacing.md,
  },
  backText: { color: colors.brandStrong, ...typography.caption, fontWeight: '700' },
  heroTags: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.sm },
  eggBadge: {
    backgroundColor: colors.surface,
    color: colors.text,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    ...typography.caption,
    overflow: 'hidden',
  },
  speciesBadge: { ...typography.caption, fontWeight: '700' },
  scopeNote: {
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  scopeTitle: { color: colors.brandStrong, ...typography.body, fontWeight: '700' },
  detailColumns: { gap: spacing.lg, marginBottom: spacing.xl },
  detailCard: { flex: 1, width: '100%' },
  stats: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginVertical: spacing.sm },
  stat: {
    backgroundColor: colors.background,
    borderRadius: radius.md,
    padding: spacing.md,
    flexBasis: '46%',
    flexGrow: 1,
    gap: spacing.xs,
  },
  statValue: { color: colors.text, fontSize: 26, lineHeight: 34, fontWeight: '800' },
  statHint: { color: colors.brandStrong, ...typography.caption, fontWeight: '700' },
  progressLabel: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  progressTrack: {
    height: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.brandSoft,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: colors.brandStrong },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.sm },
  secondaryButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.brandStrong,
    borderRadius: radius.md,
    padding: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.brandStrong,
    ...typography.caption,
    fontWeight: '700',
    textAlign: 'center',
  },
  milestone: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingTop: spacing.sm,
  },
  milestoneNumber: {
    backgroundColor: colors.brandSoft,
    minWidth: 34,
    minHeight: 34,
    padding: spacing.sm,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  milestoneNumberText: { color: colors.brandStrong, fontSize: 12, fontWeight: '800' },
  milestoneCopy: { flex: 1, gap: spacing.xs },
  milestoneTitle: { color: colors.text, ...typography.body, fontWeight: '700' },
  milestoneCount: { color: colors.brandStrong, fontSize: 12, lineHeight: 18, fontWeight: '700' },
});
