import type { components } from '@/api/generated/schema';

export const monsterFixture: components['schemas']['MonsterView'] = {
  id: 'monster-a',
  name: '말랑이',
  species: 'FOREST',
  growthStage: 'EGG',
  recognizedSuccessCount: 0,
  nextGrowthMilestone: 'HATCH',
  reachedMilestones: [],
  masteryRewards: [],
  accountLevel: 1,
  currentLevelExp: 0,
  nextLevelRequiredExp: 80,
  baseHp: 100,
  baseAttack: 10,
  equipmentBonusHp: 0,
  equipmentBonusAttack: 0,
  finalHp: 100,
  finalAttack: 10,
  combatPower: 700,
  streak: 0,
};
export const homeFixture: components['schemas']['GameHome'] = {
  serverTime: '2026-09-07T00:00:00Z',
  coupleId: 'couple-a',
  self: {
    id: 'user-a',
    nickname: '배츄친구',
    availableCoins: 1000,
    lockedCoins: 0,
    monster: monsterFixture,
  },
  partner: { id: 'user-b', nickname: '파트너', profileImage: null, monster: null },
  ownDraftCount: 0,
  questStatusSummary: { pendingApproval: 0, active: 0, awaitingResult: 0 },
};
export const draftFixture: components['schemas']['QuestDraft'] = {
  id: 'quest-a',
  coupleId: 'couple-a',
  status: 'DRAFT',
  questType: 'PERSONAL',
  sourceType: 'CUSTOM',
  rowVersion: 0,
  title: '물 한 잔 마시기',
  category: 'EATING',
  successCriteria: '자기 전에 물 한 잔을 마시기',
  difficulty: 1,
  stake: 100,
  dueAt: '2026-09-15T13:00:00Z',
  resultAt: '2026-09-16T00:00:00Z',
  minimumDurationMinutes: 0,
  evidenceMethod: 'NONE',
  approvalDeadlineAt: '2026-09-15T13:00:00Z',
  resultConfirmationDeadlineAt: '2026-09-17T00:00:00Z',
  createdAt: '2026-09-07T00:00:00Z',
  updatedAt: '2026-09-07T00:00:00Z',
};
